version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "friday"
      timezone: "Asia/Tokyo"
    versioning-strategy: "lockfile-only"
    open-pull-requests-limit: 3
