version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - reminder_bot-db-volumes:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/reminder_bot
      - reminder_bot_bundle:/usr/local/bundle
    environment:
      POSTGRES_HOST: db
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  reminder_bot-db-volumes:
  reminder_bot_bundle:
